FROM node:18-alpine as build

WORKDIR /app/frontend

COPY package.json ./ 
COPY package-lock.json ./ 
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", ""daemon off;""]